<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>smart_snippet</string>
	</array>
	<key>keyEquivalent</key>
	<string>~^S</string>
	<key>name</key>
	<string>SMART Snippet</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>(`)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.smart_snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(`)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.smart_snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>python-command.smart_snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>source.python</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>begin</key>
			<string>^((###)scope)[\t ]*(:)[\t ]*(.*)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.scope.smart_snippet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.smart_snippet</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>punctuation.smart_snippet</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>comment.scope-name.smart_snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>$</string>
			<key>name</key>
			<string>scope-definition.smart_snippet</string>
		</dict>
		<dict>
			<key>begin</key>
			<string>(\$)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.variable.smart_snippet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.smart_snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.smart_snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>variable-definition.smart_snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#snippet_key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#auto_completions</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#quick_completions</string>
				</dict>
				<dict>
					<key>match</key>
					<string>[^\}\{]*</string>
					<key>name</key>
					<string>variable.parameter.smart_snippet</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>include</key>
			<string>#auto_completions</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#quick_completions</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>auto_completions</key>
		<dict>
			<key>begin</key>
			<string>(AC)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.autocompletion.smart_snippet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.smart_snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.smart_snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>autocompletion-definition.smart_snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#completion_patterns</string>
				</dict>
			</array>
		</dict>
		<key>completion_patterns</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#snippet_key</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#snippet_param</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#snippet_param_punctuation</string>
				</dict>
			</array>
		</dict>
		<key>quick_completions</key>
		<dict>
			<key>begin</key>
			<string>(QP)(\{)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>support.function.quickcompletion.smart_snippet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.begin.smart_snippet</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>endCaptures</key>
			<dict>
				<key>0</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.smart_snippet</string>
				</dict>
			</dict>
			<key>name</key>
			<string>quickcompletion-definition.smart_snippet</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#completion_patterns</string>
				</dict>
			</array>
		</dict>
		<key>snippet_key</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>constant.other.smart_snippet</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>punctuation.end.smart_snippet</string>
				</dict>
			</dict>
			<key>match</key>
			<string>[\t ]*([\dA-Za-z\-_]*)[\t ]*(:)</string>
		</dict>
		<key>snippet_param</key>
		<dict>
			<key>match</key>
			<string>([^,: \}\{]*)</string>
			<key>name</key>
			<string>variable.parameter.snippet-param.smart_snippet</string>
		</dict>
		<key>snippet_param_punctuation</key>
		<dict>
			<key>match</key>
			<string>(,| )</string>
			<key>name</key>
			<string>punctuation.end.smart_snippet</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.smart_snippet</string>
	<key>uuid</key>
	<string>4ff3efab-65ec-42da-9670-46fd3b6ac813</string>
</dict>
</plist>